title: Minimal theme
logo: /assets/img/logo.png
description: pathogenflows is a package that predicts the flow of pathogens through sanitation systems
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
